# action.yml
name: 'Use alpine linux'
description: ''
inputs:
  pkgver:
    description: package version
    required: true
  pkgrel:
    description: package release number
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    pkgver: ${{ inputs.pkgver }}
    pkgrel: ${{ inputs.pkgrel }}
