name: Build & Upload CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * sat'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      has_update: ${{ steps.check_update.outputs.has_update }}
      pkgver: ${{ steps.check_update.outputs.pkgver }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Check tailscale Update
        id: check_update
        run: |
          pip install requests bs4
          python scripts/check_version.py

      - name: Commit & Push changes
        if: ${{ steps.check_update.outputs.has_update }} == 'true'
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{  github.ref  }}
          message: '[skip ci] auto update files with upstream.'

  build:
    needs: check
    if: needs.check.outputs.has_update == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Alpine Build APK
        uses: ./alpine-build-action
        with:
          pkgver: ${{  needs.check.outputs.pkgver  }}
          pkgrel: 1

      - name: Verify Artifacts
        run: ls packages
        
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tailscale-${{  needs.check.outputs.pkgver  }}
          path: packages/*.apk

  upload:
    needs: [check, build]
    runs-on: ubuntu-latest
    env:
      PKGVER: ${{  needs.check.outputs.pkgver  }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: tailscale-${{  env.PKGVER  }}
        path: packages

    - name: Zip and Modify Script
      run: |
        cd packages
        rm -rf ./*.zip
        zip tailscale-${{ env.PKGVER }}.zip *.apk
        rm -rf *.apk
        cd ..
        sed -i "s/PKG_VER=.*/PKG_VER=$PKGVER/g" install.sh
      
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{  github.ref  }}
