name: CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Alpine Build APK
        uses: ./alpine-build-action

      - name: Publish
        run: ls packages
        
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: apk packages
          path: ${{ github.workspace }}/packages/*.apk
          
