name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      has_update: ${{ steps.check_update.outputs.has_update }}
      pkgver: ${{ steps.check_update.outputs.pkgver }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Check tailscale Update
        id: check_update
        run: |
          pip install requests
          python scripts/check_version.py
      
  build:
    needs: check
    if: needs.check.outputs.has_update == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Alpine Build APK
        uses: ./alpine-build-action
        with:
          pkgver: ${{  needs.check.outputs.pkgver  }}
          pkgrel: 1

      - name: Verify Artifacts
        run: ls packages
        
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tailscale-${{  needs.check.outputs.pkgver  }}
          path: packages/*.apk

  upload:
    needs: [check, build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download Artifact
      uses: actions/download-artifact@v3
      env:
        PKGVER: ${{  needs.check.outputs.pkgver  }}
      with:
        name: tailscale-${{  env.PKGVER  }}
        path: packages/${{  env.PKGVER  }}
      
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{  github.ref  }}
